name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_pinata:
    runs-on: ubuntu-latest
    name: Deploy to Pinata
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Install node packages
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Pin to IPFS on Pinata
        id: deploy
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'terra-web-dapp'
          path: './build'
          verbose: true
          remove-old: false
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}

      # Use the output from the `deploy` step
      - name: Get the output hash
        run: echo "The hash was ${{ steps.deploy.outputs.hash }}"

      - name: Update CloudFlare DNS with new IPFS hash
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: ''
          RECORD_NAME: '_dnslink'
        uses: textileio/cloudflare-update-dnslink@v2
        with:
          cid: ${{ steps.deploy.outputs.hash }}
